-- https://school.programmers.co.kr/learn/courses/30/lessons/133026
SELECT I.INGREDIENT_TYPE,
    SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF FH
    LEFT JOIN ICECREAM_INFO I ON FH.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER
