-- https://school.programmers.co.kr/learn/courses/30/lessons/131536
SELECT DISTINCT A.USER_ID,
        A.PRODUCT_ID
FROM ONLINE_SALE A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
    AND A.PRODUCT_ID = B.PRODUCT_ID
    AND A.SALES_DATE != B.SALES_DATE
ORDER BY USER_ID, PRODUCT_ID DESC
