-- https://school.programmers.co.kr/learn/courses/30/lessons/144853
SELECT B.BOOK_ID,
    DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK B
WHERE YEAR(B.PUBLISHED_DATE) = 2021
    AND B.CATEGORY = '인문'
ORDER BY B.PUBLISHED_DATE